import type { Metadata } from "next";
import '@/app/globals.css';
import Sidebar from "@/components/Sidebar/Sidebar";
import Header from "@/components/Header/Header";
import { Box } from "@mui/material";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body style={{  backgroundColor: '#f9fafb'}}>
                <Box display="flex" height="100vh">
                    <Sidebar show={true} />
                    <Box flex={1} display="flex" flexDirection="column">
                        <Header />
                        <Box padding={10} paddingY={8} paddingX={16}>
                            {children}
                        </Box>
                    </Box>
                </Box>
            </body>
        </html>
    );
}
